#!/bin/bash

module load intel/15.0.6 mpi/intel/5.0.3.049
module load cp2k/4.1

NAME=pt

i=20000
while [ $i -le 45600 ]
do

cat ./inp1 ./coords.$i ./inp2 > inp.$i

mpiexec.hydra cp2k.popt inp.$i > out.$i

cp $NAME-v_hartree-1_0.cube  pot-$i.cube

i=$((i+200))

done 
